import turtle

t=turtle.Turtle()
turtle.speed(2)

turtle.pencolor("Purple")
turtle.fillcolor("Red")
turtle.begin_fill()

turtle.left(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(20)
turtle.right(45)
turtle.forward(20)
turtle.left(90)
turtle.forward(20)
turtle.right(45)
turtle.forward(20)
turtle.right(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(80)
turtle.left(90)
turtle.forward(10)
turtle.left(45)
turtle.forward(20)
turtle.right(90)
turtle.forward(20)
turtle.left(45)
turtle.forward(10)
turtle.left(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(20)
turtle.end_fill()
turtle.hideturtle()
turtle.end_fill()
turtle.done()